export const landingCourses = [
  {
    slug: 'product-management',
    title: 'Product Management',
    tagline: 'Modern Product Teams — from discovery to go-to-market.',
    category: 'product',
    level: 'Beginner',
    cover: 'from-indigo-700 to-blue-500',
    lessonCount: 29,
    totalMin: 177,
  },
  {
    slug: 'data-analytics',
    title: 'Data Analytics',
    tagline: 'From data science to dashboards — make decisions with data.',
    category: 'data',
    level: 'Beginner',
    cover: 'from-fuchsia-700 to-pink-500',
    lessonCount: 24,
    totalMin: 126,
  },
  {
    slug: 'agentic-ai',
    title: 'Agentic AI',
    tagline: 'Build with LLMs, agents and automation — the Requisor way.',
    category: 'ai',
    level: 'Beginner',
    cover: 'from-teal-700 to-cyan-500',
    lessonCount: 21,
    totalMin: 1192,
  },
  {
    slug: 'cyber-security',
    title: 'Cyber Security',
    tagline: 'Defend Requisor — from networking basics to incident response.',
    category: 'security',
    level: 'Beginner',
    cover: 'from-blue-800 to-blue-600',
    lessonCount: 9,
    totalMin: 169,
  },
]