import { ClipboardList, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";
import { SUBMISSION_SOURCE_LABEL, type SubmissionSource } from "@/lib/submission-source";

const STYLES: Record<SubmissionSource, { className: string; Icon: typeof Sparkles; title: string }> = {
  tutor: {
    className: "bg-primary/10 text-primary ring-primary/20",
    Icon: ClipboardList,
    title: "The assignment you set for this lesson",
  },
  ai: {
    className: "bg-violet-50 text-violet-700 ring-violet-600/20",
    Icon: Sparkles,
    title: "A practice assignment generated by AI for this learner",
  },
};

/** Tells tutors at a glance whether work answers their own assignment or an AI practice brief. */
export function SubmissionSourceBadge({ source, className }: { source: SubmissionSource; className?: string }) {
  const { className: tone, Icon, title } = STYLES[source];
  return (
    <span
      title={title}
      className={cn("inline-flex shrink-0 items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-medium ring-1 ring-inset", tone, className)}
    >
      <Icon className="h-3 w-3" aria-hidden="true" />
      {SUBMISSION_SOURCE_LABEL[source]}
    </span>
  );
}
